### ISSUE TITLE
Crear fichero js

### ISSUE THREAD

**Issue by JoseLuisCarvajal** [rubenzc/FillFormDataImagesWP#1]
Dentro o no de una carpeta, como quieras. Y pegas el código que llevas por ahora.

Esta es la primera tarea chispas ;)

**Comment by rubenzc** [comment]
Ya está creado y te he añadido como colaborador. Le voy a dar una vuelta al primer código y estructurarlo mucho mejor

**Comment by JoseLuisCarvajal** [comment]
Oka. Genial. Esta tarea la puedes cerrar.
