### ISSUE TITLE
Añadir atributos a los inputs del formulario.

### ISSUE THREAD

**Issue by JoseLuisCarvajal** [rubenzc/FillFormDataImagesWP#2]
- Añadir atributo id (incluso al button)
- Atributo placeholder (o usar un label con un atributo for que se asocie con cada input) por ahora lo que prefieras.
- Poner a vacío los atributos value.

Seguramente que necesitemos en un futuro más atributos, por ahora tiramos con estos.

**Comment by rubenzc** [comment]
"Usar un label con un atributo for que se asocie con cada input". Esto me lo tienes que explicar que  no lo acabo de entender. Entiendo que es un bucle que va asignando a cada input un label?

Ya están añadidos los atributos

**Comment by JoseLuisCarvajal** [comment]
Esto no lo necesitamos realmente porque nos apañaríamos con los placeholder. Pero mira, así ves lo del for.
Me refería a añadir un label asociado a cada input. Tipo nombre: ```<input>```
Puedes.... meter el tag input dentro del label: ```<label>nombre <input type=text...../></label>```
o ```<label for=inputID>nombre</label><input id=inputID ...../>```
Esto hace que se relaccionen, hasta el punto que un click sobre el label pone el foco en el cursor....
Y rollos de accesibilidad... en fin, un form super correcto. Aunque le metas también el placeholder.

**Comment by JoseLuisCarvajal** [comment]
Joder, se ha cargado el html que he metido en el comment. Por eso se lee tan raro :)

**Comment by JoseLuisCarvajal** [comment]
Ahora
