### ISSUE TITLE
Añadir algo de marcado que agrupe lo que llevamos.

### ISSUE THREAD

**Issue by JoseLuisCarvajal** [rubenzc/FillFormDataImagesWP#3]
Por ahora, podemos meter los elementos de formulario dentro de un form y este a su vez dentro de un div.
Así luego sólo hacemos un único append al body.

Un div que en un futuro cuando le demos algo de estilos será la capa que ocupa todo el viewport. Con un backgroud, opacity .5... ya sabes. 
Y luego el form. Que aunque no lo vamos a usar como tal. Ya lo metemos.
Luego veremos si necesitamos más cajas para decorar. Pero hazlo sólo si estás parado. Porque los estilos nos la sudan por ahora. No dejes que te pueda eso. Mejor llegar a chicha javascript.

**Comment by rubenzc** [comment]
He cambiado la estructura y añadido estilos. Tengo un problema a la hora de cargar estilos dado que no se si es correcto el orden como está colocado porque cargan cuando lanzas el script por segunda vez. Lo he probado con estilos independientes y con los estilos de bootstrap por CDN y me pasa lo mismo.

**Comment by JoseLuisCarvajal** [comment]
Efectivamente, estás añadiendo estilos a elementos que todavía no existen en el dom. Hay que cambiar el orden. Pero está guay que los añadas así, porque lo dejas más limpio. Yo te decía meterlos usando el atributo style sobre el tag. Pero queda mucho mejor así.
Lo cambio yo y aprovecho para hacer un commit.
